Update randomuser entry
typicalbot/docs pull request #1
Opened 2020-07-30 14:56 UTC by TobiasFeld22

- Include the new amount selector.
- Update -o to show what it means.

2020-07-30 15:10 UTC, tjrgg requested changes

2020-07-30 15:10 UTC, tjrgg commented on docs/commands/utility/randomuser.md
> +Selects a random member in the server.
```suggestion
Selects a random member in the server.
```

2020-07-30 15:10 UTC, tjrgg commented on docs/commands/utility/randomuser.md
> + - `$randomuser [-online/-o]`
```suggestion
 - `$randomuser [-online/-o]`
```

2021-11-16 21:55 UTC, nsylke commented
Closing due to stale PR

2021-11-16 21:55 UTC, closed without merging