Update hug.md
typicalbot/docs pull request #3
Opened 2020-12-22 06:45 UTC by shreyash00007

Well sir, I just created a folder for the images and uploaded one Hope you like it I can 
Do this for all commands.

2021-01-07 15:36 UTC, tjrgg commented on docs/commands/fun/hug.md
> + ![](https://github.com/shreyash00007/docs/blob/master/Img/hug.PNG)
This appears to link to an image in your fork that is not included in this PR.

2021-01-07 15:37 UTC, tjrgg requested changes
An image you've linked to comes from your fork and wasn't included in the PR.

2021-01-07 15:37 UTC, tjrgg commented on docs/commands/fun/hug.md
> + ![](https://github.com/shreyash00007/docs/blob/master/Img/hug.PNG)
This appears to link to an image in your fork that is not included in this PR.

2021-01-07 15:49 UTC, shreyash00007 commented
> An image you've linked to comes from your fork and wasn't included in the PR.

For that I need to give the images to you I will submit all the images by tomorrow.

2021-11-16 21:55 UTC, nsylke commented
Closing due to stale PR

2021-11-16 21:55 UTC, closed without merging